### ISSUE TITLE
Hassio reinstalls libaries with every restart of homeassistant

### ISSUE THREAD

**Issue by frog32** [home-assistant/hassio-homeassistant#11]
Since the latest beta i observ longer restart times. Looking at the logs it seem that it reinstalls libaries like SoCo, pychromecast and others after every restart.

**Comment by pvizeli** [comment]
Remove the dept folder inside config

**Comment by frenck** [comment]
@frog32 That should fix the problem. I'll close this issue for now. If it doesn't solve the issue, feel free to re-open it again, or hop on onto our Discord server for support.

**Comment by frog32** [comment]
This resolved the issue. I remember that there was an issue in 0.77b1 that probably triggered this and ever since it was installing packets.

I wonder how many others that follow the beta channel are affected by this.
