### ISSUE TITLE
Addons not installing

### ISSUE THREAD

**Issue by nismanoke** [home-assistant/hassio-homeassistant#14]
Hi,

Did a fresh hassio install (flashed sd card with hassio 1.10). But when trying to install addons from official as well community repository i get "addon not installed". I tried  a few addons like portainer, node-red, mosquitto and zigbee2mqtt.

I added a few screenshots.

If additional info is needed please request.

**Edit**
I tried the 64 bit image for rpi-3 and had no problems installing addons only with the 32 bit version

Node-Red install failed
![schermopname 7](https://user-images.githubusercontent.com/16641049/45910473-aeb6d180-be09-11e8-88f2-75729c95a8e9.png)

Zigbee2mqtt install failed
![schermopname 3](https://user-images.githubusercontent.com/16641049/45910481-c7bf8280-be09-11e8-952d-1eb51b5b7711.png)

**Comment by pvizeli** [comment]
wrong repository
