### ISSUE TITLE
python3 segfaults in latest version of base image (alpine:3.9) on aarch64

### ISSUE THREAD

**Issue by campbellr** [home-assistant/hassio-homeassistant#26]
It looks like now that the base images are based on Alpine 3.9, it is causing some issues at keast ibe addon (`samccauley/addon-hassiogooglebackup`). Specifically, `python3` is now segfaulting we attempt to run it.

The previous version of the base image (`homeassistant/aarch64-homeassistant-base:20181114`, based on Alpine 3.8) seems to work fine.

See also:
* https://bugs.alpinelinux.org/issues/9981
* https://github.com/samccauley/addon-hassiogooglebackup/issues/8

**Comment by pvizeli** [comment]
you can use our python base images. I think that will fix that. We don't use the python from apk: https://github.com/home-assistant/hassio-base

I close that because they have no effect on Home Assistant. Thanks for reporting

**Comment by campbellr** [comment]
Thanks!
