### ISSUE TITLE
Rasberry Pi Zero W - 0.89.1 doesn't start after card flashing 

### ISSUE THREAD

**Issue by barthand** [home-assistant/hassio-homeassistant#28]
Hey,

First of all, many thanks for your great work! I <3 HA and I very much appreciate what you're doing.

There is a problem though with Docker image `homeassistant/raspberrypi-homeassistant`, version: `0.89.1`. On Raspberry Pi Zero W, after flashing SD card, supervisor is not able to pull the latest image (indeed 0.89.1 as of time of writing), because Docker returns error:

```
manifest for homeassistant/raspberrypi-homeassistant:0.89.1 not found
```

BTW, is there a way to force hassio to pull other image than `latest` after flashing SD card?

**Comment by pvizeli** [comment]
They work with 0.89.2 ?

**Comment by barthand** [comment]
Eventually, I managed to force to run earlier version (0.88.2) after flashing SD, just by manually pulling the image and restarting the Pi Zero. It simply seemed supervisor picked up this manually downloaded version and run it. 

After 0.89.2 release, I successfully updated from 0.88.2 to it (from GUI), so I'm assuming this release has been properly pushed to dockerhub.

**Comment by frenck** [comment]
Thanks for letting us know @barthand! And sorry for the inconvenience that it might have cost.
