### ISSUE TITLE
HA version 3.2.7 is not working on Docker and Raspberry Pi 3

### ISSUE THREAD

**Issue by mwolfaardt** [home-assistant/hassio-homeassistant#51]
Hi, I pulled the latest docker image (homeassistant/raspberrypi3-homeassistant:latest)  and recreated my docker container. After starting the container I get the following errors from the logs : 

starting version 3.2.7
Command not found: 'python3'

**Comment by pvizeli** [comment]
Use a version tag and not the latest. Looks like your client get an old version

**Comment by mwolfaardt** [comment]
I've tried with multiple versions and still get the same issue.

**Comment by mwolfaardt** [comment]
Got it working, was CMD in portainer that was incorrect
