### ISSUE TITLE
intelnuc packages for gpu acceleration 

### ISSUE THREAD

**Issue by djaydev** [home-assistant/hassio-homeassistant#82]
For the hassio Intel nuc install, it contains ffmpeg with vaapi support that works with the nuc's igpu but it's missing the packages libva & libva-intel-driver. Can those be added to the dockerfile or is there a way to have my system add it automatically through upgrades/rebuilds?
thanks

**Comment by pvizeli** [comment]
https://github.com/home-assistant/hassio-homeassistant/blob/master/machine/intel-nuc

Feel free to add this. But please test it before, it's annoying how many people make PR without test it, and I need to fix all the stuff.
