### ISSUE TITLE
Ping doesn't work if home assistant running as non root user 

### ISSUE THREAD

**Issue by definitio** [home-assistant/hassio-homeassistant#91]
There is a problem with alpine images that prevents executing 'ping' as non root user. It breaks wake_on_lan integration for me.

I know that it's unsupported configuration but maybe it can be fixed anyway?
There is simple workaround: add `RUN chmod u+s /bin/ping` to Dockerfile.
Can it be added?

**Comment by pvizeli** [comment]
> I know that it's unsupported configuration

And we did not support it. Feel free to use i.e. the nmap integration. You need run home assistant inside venv if you don't want run it as docker. So you can modify the script and fix the ping sensor before you change the permission and start HA on different user: https://github.com/home-assistant/home-assistant/issues/24397
